project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!docker/"

resources:
  - docker/**/*.yaml

website:
  title: "CRISalid Deployment Documentation"
  description: "Resources and documentation for deploying CRIS modules built by the CRISalid community"
  site-url: https://docs.crisalid.org  # Optional, adjust if hosted
  favicon: assets/favicon.ico          # Optional, place your favicon here
  page-navigation: true

  navbar:
    left:
      - href: index.qmd
        text: 🏠 Home
      - sidebar:crisalid-core
      - sidebar:crisalid-ai
      - sidebar:security
    right:
      - text: 🌐 Website
        href: https://crisalid.org/
      - text: 🧭 Wiki
        href: https://www.esup-portail.org/wiki/spaces/ESUPCRISalid/overview
      - text: 🐳 DockerHub
        href: https://hub.docker.com/repositories/crisalidesr
      - text: GitHub
        icon: file-code
        href: https://github.com/orgs/CRISalid-esr/repositories

  sidebar:
    - id: crisalid-core
      title: "💠 Crisalid Core"

      contents:
        - section: "Overview"
          contents:
            - map/index.qmd
            - map/components.qmd
            - map/harvesting.qmd
            - map/message_catalog.qmd
        - section: "Docker Compose"
          contents:
            - dev/index.qmd
            - href: dev/docker-compose.qmd
              text: "Docker Compose - Overview"
            - href: dev/step-by-step.qmd
              text: "Docker Compose - Step by Step"
            - dev/dev-backend.qmd
            - dev/local-tls.qmd
            - dev/export-kc-realm.qmd
            - dev/backup-restore-with-dc.qmd
            - dev/manual_installation.qmd
        - section: "Kubernetes"
          contents:
            - prod/index.qmd
            - prod/helm_charts.qmd
            - prod/manual_installation.qmd
        - section: "Requirements"
          contents:
            - requirements/index.qmd
    - id: crisalid-ai
      title: "🤖 Crisalid AI"

      contents:
        - section: "Overview"
          contents:
            - ai/index.qmd
            - ai/security.qmd
        - section: "Installation"
          contents:
            - ai/local-workstation.qmd
            - ai/docker-compose.qmd
            - href: ai/using-skills.qmd
              text: "Using CRISalid AI Skills"
            - ai/configuring-openwebui.qmd
            - href: ai/embeddings.qmd
              text: "Semantic Embeddings"
    - id: security
      title: "🔒 Security"

      contents:
        - security/index.qmd

format:
  html:
    theme: default
    highlight: tango
    css: index.css
    code-fold: true
    toc: true
    toc-title: Table of Contents
    toc-location: left
    toc-expand: true
    smooth-scroll: true
