services:
  apollo:
    image: crisalidesr/crisalid-apollo:latest
    ports:
      - ${APOLLO_API_PORT}:4000
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - APP_ENV=DEV
      - NEO4J_URI=bolt://neo4j:${NEO4J_BOLT_PORT}
      - ENABLE_API_KEYS=${APOLLO_ENABLE_API_KEYS}
    profiles:
      - apollo
